version: '3.8'

services:
  nextjs-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_SOCKET_IO_URL=http://socket-io:3001

  socket-io:
    build:
      context: ./socket-io
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
