import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import './globals.css'
import LogOutModal from '@/components/modals/log-out-modal'
import ThemeProvider from '@/components/theme-provider'
import { AuthContextProvider } from '@/context/auth/auth-context'
import { IsEditingContextProvider } from '@/context/chat/is-editing-context'
import { DeleteChannelModalContextProvider } from '@/context/delete-channel-context'
import { EditChannelModalContextProvider } from '@/context/edit-channel-context'
import { ModalContextProvider } from '@/context/modal-context'
import { ServerSettingsContextProvider } from '@/context/settings/server-settings-context'
import { UserSettingsContextProvider } from '@/context/settings/user-settings-context'
import { SocketContextProvider } from '@/context/socket-context'
import { cn } from '@/lib/utils'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dazzlecord',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={cn(
      font.className,
      'bg-page',
      'dark:bg-page-dark',
    )}
    >
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <AuthContextProvider>
          <ModalContextProvider>
            <EditChannelModalContextProvider>
              <DeleteChannelModalContextProvider>
                <SocketContextProvider>
                  <ServerSettingsContextProvider>
                    <UserSettingsContextProvider>
                      <IsEditingContextProvider>
                        {children}
                        <LogOutModal />
                      </IsEditingContextProvider>
                    </UserSettingsContextProvider>
                  </ServerSettingsContextProvider>
                </SocketContextProvider>
              </DeleteChannelModalContextProvider>
            </EditChannelModalContextProvider>
          </ModalContextProvider>
        </AuthContextProvider>
      </ThemeProvider>
    </body>
  </html>
)

export default RootLayout
