import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { ServerModalContextProvider } from '@/context/serverModalContext'
import { cn } from '@/lib/utils'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Deezcord',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        font.className,
        'bg-white',
        'dark:bg-[#313338]',
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ServerModalContextProvider>
            {children}
          </ServerModalContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
